### ISSUE TITLE
Create User Auth Service

### ISSUE THREAD

**Issue by 50-Course** [Koobo-app/koobo-core#6]
User Authentication as Service :+1: 
I want to be able to regiser with my social accounts

**Comment by MrAzuka** [comment]
With social account? 
YOu mean social media accounts right?
Are we creating our own customised login

**Comment by MrAzuka** [comment]
With social account? 
YOu mean social media accounts right?
Are we creating our own customised login

**Comment by 50-Course** [comment]
We are working with custoized login for now. OAuth has been removed from the design. Would you like to work on this?
